class TabelaTokens:
    def __init__(self):
        self.tabela_tokens = {
            "programa" : "sprograma",
            "inicio" : "sinicio",
            "fim" : "sfim",
            "procedimento" : "sprocedimento",
            "funcao" : "sfuncao",
            "se" : "sse",
            "entao" : "sentao",
            "senao" : "ssenao",
            "enquanto" : "senquanto",
            "faca" : "sfaca",
            ":=" : "satribuição",
            "escreva" : "sescreva",
            "leia" : "sleia",
            "var" : "svar",
            "inteiro" : "sinteiro",
            "booleano" : "sbooleano",
            "identificador" : "sidentificador",
            "numero" : "snumero",
            "." : "sponto",
            ";" : "sponto_vírgula",
            "," : "svírgula",
            "(" : "sabre_parênteses",
            ")" : "sfecha_parênteses",
            ">" : "smaior",
            ">=" : "smaiorig",
            "=" : "sig",
            "<" : "smenor",
            "<=" : "smenorig",
            "!=" : "sdif",
            "+" : "smais",
            "-" : "smenos",
            "*" : "smult",
            "div" : "sdiv",
            "e" : "se",
            "ou" : "sou",
            "nao" : "snao",
            ":" : "sdoispontos",
            "ERRO": "serro"
        }
    
